// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BoardgamereviewTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void boardgamereview()
    {
        driver.Navigate().GoToUrl("https://boardgamegeek.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
        driver.FindElement(By.LinkText("Sign In")).Click();
        driver.FindElement(By.Id("inputUsername")).Click();
        driver.FindElement(By.Id("inputUsername")).SendKeys("blabla111");
        driver.FindElement(By.Id("inputPassword")).Click();
        driver.FindElement(By.Id("inputPassword")).SendKeys("thisispassword");
        driver.FindElement(By.Id("inputPassword")).SendKeys(Keys.Enter);
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
        IWebElement accountMenu = driver.FindElement(By.XPath("/html/body/gg-app/div/gg-header/header/nav/div/div[1]/div/div[2]/gg-menu-nav-user/ul/li[2]/gg-my-geek/div/button/span[2]"));

        accountMenu.Click();

        IWebElement searchBar = driver.FindElement(By.Id("1"));
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
        searchBar.Click();
        searchBar.SendKeys("Pandemic Legacy Season 1");
        searchBar.SendKeys(Keys.Enter);
        IWebElement gameName1 = driver.FindElement(By.XPath("/html/body/div[2]/main/div/div[1]/div[1]/div/div/div[3]/div[3]/table/tbody/tr[2]/td[3]/div[2]/a"));

        gameName1.Click();

        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

        
        driver.FindElement(By.CssSelector(".glyphicon:nth-child(16)")).Click();
        driver.FindElement(By.Id("comment")).Click();
        driver.FindElement(By.Id("comment")).SendKeys("good game");
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".game-action > .btn-subtle:nth-child(1)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            //var element = driver.FindElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            //builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.XPath("/html/body/div[2]/main/div/div[1]/div[1]/div[2]/ng-include/div/ng-include/div/div[2]/div[2]/div[4]/span[1]/div/div/span[1]/span/span/i[8]")).Click();
        driver.FindElement(By.CssSelector(".rating-stars-clear")).Click();
        driver.FindElement(By.CssSelector(".modal")).Click();
        driver.FindElement(By.CssSelector(".modal-footer > .ng-binding:nth-child(2)")).Click();
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        driver.FindElement(By.CssSelector(".mygeek-dropdown-username")).Click();
        driver.FindElement(By.LinkText("Sign Out")).Click();

    }
}
