// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BookmarkTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bookmark() {
    driver.Navigate().GoToUrl("https://boardgamegeek.com/boardgame/174430/gloomhaven");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector(".global-header-nav-primary > .ng-isolate-scope:nth-child(1) > .btn")).Click();
    driver.FindElement(By.LinkText("All Boardgames")).Click();
    driver.FindElement(By.LinkText("Gloomhaven")).Click();
    {
      var element = driver.FindElement(By.LinkText("Josh T. McDowell"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".toolbar-actions > .toolbar-action .ng-scope .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      //var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".toolbar-actions .ng-scope .hidden-xs")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".has-rating-8"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      //var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Id("inputUsername")).Click();
    driver.FindElement(By.Id("inputUsername")).SendKeys("blabla111");
    driver.FindElement(By.Id("inputPassword")).Click();
    driver.FindElement(By.Id("inputPassword")).SendKeys("thisispassword");
    driver.FindElement(By.Id("inputPassword")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".toolbar-actions .ng-scope .hidden-xs")).Click();
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(1) > .checkbox:nth-child(1) .ng-pristine")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.CssSelector(".global-header-nav-primary > .ng-scope:nth-child(1) > .btn")).Click();
    driver.FindElement(By.LinkText("All Boardgames")).Click();
    driver.FindElement(By.LinkText("Pandemic Legacy: Season 1")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".toolbar-actions > .toolbar-action .ng-scope .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".toolbar-actions > .toolbar-action .ng-scope .btn")).Click();
    {
     // var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(1) > .checkbox:nth-child(1) .ng-pristine")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.CssSelector(".global-header-nav-primary > .ng-scope:nth-child(1) > .btn")).Click();
    driver.FindElement(By.LinkText("All Boardgames")).Click();
    driver.FindElement(By.LinkText("Brass: Birmingham")).Click();
    {
      var element = driver.FindElement(By.LinkText("See Full Credits"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
     // var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".toolbar-actions > .toolbar-action .ng-scope .btn"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".toolbar-actions > .toolbar-action .ng-scope .btn")).Click();
    {
     // var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
     // builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".col-sm-6:nth-child(1) > .checkbox:nth-child(1) .ng-pristine")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    driver.FindElement(By.CssSelector(".mygeek-dropdown-username")).Click();
    driver.FindElement(By.LinkText("Collection")).Click();
  }
}
