// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BuystuffTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void buystuff() {
    driver.Navigate().GoToUrl("https://boardgamegeek.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.LinkText("Sign In")).Click();
    driver.FindElement(By.Id("inputUsername")).Click();
    driver.FindElement(By.Id("inputUsername")).SendKeys("blabla111");
    driver.FindElement(By.Id("inputPassword")).Click();
    driver.FindElement(By.Id("inputPassword")).SendKeys("thisispassword");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(6);
        driver.FindElement(By.XPath("/html/body/gg-app/div/gg-header/header/nav/div/div[1]/div/div[2]/gg-menu-nav-user/ul/li[2]/gg-my-geek/div/button")).Click();
        IWebElement CommunityButton = driver.FindElement(By.XPath("/html/body/gg-app/div/gg-header/header/nav/div/div[1]/div/div[1]/ul/li[4]/button"));
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(6);
        CommunityButton.Click();
    driver.FindElement(By.LinkText("Geek Market")).Click();
    driver.FindElement(By.Id("itemsearch")).Click();
    driver.FindElement(By.Id("itemsearch")).SendKeys("pandemic legacy");
    driver.FindElement(By.Id("itemsearch")).SendKeys(Keys.Enter);
        driver.FindElement(By.XPath("/ html / body / div[2] / div / div / div / div[5] / div / div[3] / div / a")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".fa-list"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      Actions builder = new Actions(driver);
    }
    {
      var element = driver.FindElement(By.CssSelector(".btn-xs:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      //var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-group > .ng-binding")).Click();
    driver.FindElement(By.LinkText("Price (lowest first)")).Click();
    driver.FindElement(By.LinkText("Pandemic Legacy: Season 1")).Click();
    driver.FindElement(By.CssSelector(".btn-cart")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".label"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".label")).Click();
    driver.FindElement(By.LinkText("Proceed to checkout")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".fa-shopping-cart"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".fa-shopping-cart")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(1) .nav-label")).Click();
    driver.FindElement(By.CssSelector(".mygeek-dropdown-username")).Click();
    driver.FindElement(By.LinkText("Sign Out")).Click();
  }
}
