// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class FindagoodgamenavigatewithoutusingkeyboardcanyoufindwhatyoulookforinseveralwaysTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void findagoodgamenavigatewithoutusingkeyboardcanyoufindwhatyoulookforinseveralways() {
    driver.Navigate().GoToUrl("https://boardgamegeek.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector(".dropdown-primary:nth-child(1) > .dropdown-toggle")).Click();
    driver.FindElement(By.LinkText("Categories")).Click();
    driver.FindElement(By.LinkText("Medical")).Click();
    driver.FindElement(By.CssSelector(".rec-grid-item:nth-child(1) .rec-title")).Click();
    driver.FindElement(By.CssSelector(".global-header-nav-primary > .ng-isolate-scope:nth-child(1) > .btn")).Click();
    driver.FindElement(By.LinkText("Publishers")).Click();
    driver.FindElement(By.CssSelector("p > a:nth-child(7)")).Click();
    driver.FindElement(By.CssSelector("p > a:nth-child(6)")).Click();
    driver.FindElement(By.LinkText("Z-Man Games")).Click();
    driver.FindElement(By.CssSelector(".rec-grid-item:nth-child(1) .rec-title")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".ng-scope > .ng-scope > a:nth-child(1) > .img-responsive"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".global-header-nav-primary > .ng-isolate-scope:nth-child(1) > .btn")).Click();
    driver.FindElement(By.LinkText("All Boardgames")).Click();
    driver.FindElement(By.LinkText("Pandemic Legacy: Season 1")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn > .ng-binding:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
