// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WhatisthesongcalledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void whatisthesongcalled() {
    driver.get("https://www.spotify.com/se/");
    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.cssSelector(".ButtonInner-peijbp-0")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Sök")).click();
    driver.findElement(By.cssSelector(".QO9loc33XC50mMRUCIvf")).sendKeys("darude");
    driver.findElement(By.cssSelector(".\\_gB1lxCfXeR8_Wze5Cx9")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".eRuZMo_HNLjb1IalIeRb"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.cssSelector(".playback-bar__progress-time-elapsed"), "0:25"));
    }
    driver.findElement(By.cssSelector(".A8NeSZBojOQuVvK4l1pS path")).click();
  }
}
